name: Delivery Test

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Write Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
            [
            {
              "id": "github",
              "name": "github",
              "url": "https://maven.pkg.github.com/edoardopelli/joinup-commons",
              "releases": {
                "enabled": "true"
              }
            }
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "${env.GIT_USERNAME}",
                "password": "${env.GITHUB_TOKEN}",
                "configuration": {
                "httpConfiguration": {
                    "all": {
                      "usePreemptive": "true"
                    }
                  }
                }
              }
            ]



      - name: Maven Snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USERNAME: edoardopelli
        run: mvn -s /home/runner/.m2/settings.xml  clean install -U  -DskipTests
      

      - name: Get metadata from pom.xml
        if: ${{ success() }}
        run: |
          REPO=$(mvn -q -Dexec.executable=echo  -Dexec.args='${project.artifactId}' --non-recursive exec:exec)
          VERSION=$(mvn -q -Dexec.executable=echo  -Dexec.args='${project.version}' --non-recursive exec:exec)

          echo "REPO=$REPO" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

        shell: bash
        
      - name: Build Docker Image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image edoardopelli/${{ env.REPO }}:${{ env.VERSION }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: edoardopelli/${{ env.REPO }}:${{ env.VERSION }}
          build-args: |
            version=${{ env.VERSION }}

    